name: noschecker
services:
  backend:
    build:
      context: be
      target: production
    environment:
      - ASSIGNMENTS=/data/assignments.json
      - SUBMISSIONS=/data/submissions.csv
      - DOWNLOADS=/downloads
      # - PASSWORD
      # - JWT_KEY
    volumes:
      - ./db/assignments.json:/data/assignments.json
      - ./db/submissions.csv:/data/submissions.csv
      - ./downloads:/downloads
    ports:
      - 8080:8080
  frontend:
    build:
      context: fe
      target: production
      args:
        - VITE_API_HOST=http://172.104.50.136:8080
    ports:
      - 80:80
