name: noschecker
services:
  backend:
    build:
      context: be
      target: production
    environment:
      - ASSIGNMENTS=/data/assignments.json
      - SUBMISSIONS=/data/submissions.csv
      - DOWNLOADS=/downloads
    volumes:
      - ./db/assignments.json:/data/assignments.json
      - ./db/submissions.csv:/data/submissions.csv
      - ./downloads:/downloads
    ports:
      - 8080:8080
  frontend:
    build:
      context: fe
      target: production
    ports:
      - 80:80


